server.port=${PORT:8080}

# H2 DATABASE
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true

# JWT
jwt.secret=default-secret
jwt.expiration-ms=86400000

# Disable mail (avoid crash)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Disable Google (safe)
google.oauth.client-id=dummy
google.oauth.client-secret=dummy
google.oauth.redirect-uri=http://localhost:8080

# Logging
logging.level.root=WARN

server.servlet.context-path=/api
